version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  warehouse:
    build: ./warehouse
    ports:
      - '8081:8081'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
  storefront:
    build: ./storefront
    ports:
      - '8080:8080'
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - WAREHOUSE_URL=http://warehouse:8081
    depends_on:
      - rabbitmq
      - warehouse
